name: Bug Report
description: Report a bug in blitz-io
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: input
    id: zig-version
    attributes:
      label: Zig Version
      description: Output of `zig version`
      placeholder: "0.15.2"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows 10
        - Windows 11
    validations:
      required: true

  - type: dropdown
    id: backend
    attributes:
      label: I/O Backend
      description: Which backend is affected?
      options:
        - All backends
        - io_uring (Linux)
        - epoll (Linux)
        - kqueue (macOS)
        - IOCP (Windows)
        - Unknown / Auto-detected
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Backend / Driver
        - TCP Networking
        - Unix Sockets
        - File I/O
        - Synchronization Primitives
        - Runtime / Scheduler
        - Blocking Pool
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal code or steps to reproduce the issue
      placeholder: |
        ```zig
        const blitz = @import("blitz-io");

        pub fn main() !void {
            var rt = try blitz.Runtime.init(allocator, .{});
            defer rt.deinit();

            // Code that triggers the bug...
        }
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (include error messages, stack traces if any)
    validations:
      required: true

  - type: input
    id: kernel-version
    attributes:
      label: Kernel Version (Linux only)
      description: Output of `uname -r` (important for io_uring issues)
      placeholder: "5.15.0-generic"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context (logs, test output, etc.)
